language: python

cache:
  directories:
  - lua_install
  - testrun/testing_cache-5.1
  - testrun/testing_cache-5.2
  - testrun/testing_cache-5.3
  - testrun/testing_cache-2.1
  - testrun/testing_server-5.1
  - testrun/testing_server-5.2
  - testrun/testing_server-5.3
  - testrun/testing_server-2.1
  - testrun/binary-samples
  
unit_script: &unit_script
  - busted -o gtest --exclude-tags=git,integration --verbose -Xhelper "lua_dir=$PWD/lua_install,travis"
  - busted -o gtest --exclude-tags=git,integration --verbose -Xhelper "lua_dir=$PWD/lua_install,travis,env=full"
  
integration_script: &integration_script
  - lua -v
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then shellcheck ./configure; fi
  - ./configure --with-lua=lua_install
  - ./makedist dev
  - busted -o gtest --exclude-tags=gpg,git,unit --verbose -Xhelper "lua_dir=$PWD/lua_install,travis"
  - busted -o gtest --exclude-tags=gpg,git,unit --verbose -Xhelper "lua_dir=$PWD/lua_install,travis,env=full"
          
jobs:
  include:
    # Unit tests for linux
    - stage: unit
      script: *unit_script
      os: linux
      env:
        - LUA="lua=5.1"
    - stage: unit
      script: *unit_script
      os: linux
      env:
        - LUA="lua=5.2"
    - stage: unit
      script: *unit_script
      os: linux
      env:
        - LUA="lua=5.3"
    - stage: unit
      script: *unit_script
      os: linux
      env:
        - LUA="luajit=2.1"
    # Unit tests for osx
    - stage: unit
      script: *unit_script
      os: osx
      env:
        - LUA="lua=5.1"
      language: generic
    - stage: unit
      script: *unit_script
      os: osx
      env:
        - LUA="lua=5.2"
      language: generic
    - stage: unit
      script: *unit_script
      os: osx
      env:
        - LUA="lua=5.3"
      language: generic
    - stage: unit
      script: *unit_script
      os: osx
      env:
        - LUA="luajit=2.1"
      language: generic
    # Integration tests for linux
    - stage: integration
      script: *integration_script
      os: linux
      env:
        - LUA="lua=5.1"
    - stage: integration
      script: *integration_script
      os: linux
      env:
        - LUA="lua=5.2"
    - stage: integration
      script: *integration_script
      os: linux
      env:
        - LUA="lua=5.3"
    - stage: integration
      script: *integration_script
      os: linux
      env:
        - LUA="luajit=2.1"
    # Integration tests for osx
    - stage: integration
      script: *integration_script
      os: osx
      env:
        - LUA="lua=5.1"
      language: generic
    - stage: integration
      script: *integration_script
      os: osx
      env:
        - LUA="lua=5.2"
      language: generic
    - stage: integration
      script: *integration_script
      os: osx
      env:
        - LUA="lua=5.3"
      language: generic
    - stage: integration
      script: *integration_script
      os: osx
      env:
        - LUA="luajit=2.1"
      language: generic
              
before_install:
  - if [ ! -f lua_install/bin/luarocks ]; then pip2 install hererocks; fi
  - if [ ! -f lua_install/bin/luarocks ]; then hererocks lua_install -r^ --$LUA; fi
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH

install:
  - if [ ! -f lua_install/bin/busted ]; then luarocks install busted; fi
  - if [ ! -f lua_install/bin/luacov ]; then luarocks install cluacov; fi

after_success:
  - luacov -c $TRAVIS_BUILD_DIR/testrun/luacov.config
  - cd $TRAVIS_BUILD_DIR/testrun/ && bash <(curl -s https://codecov.io/bash)
  - grep "Summary" -B1 -A1000 $TRAVIS_BUILD_DIR/testrun/luacov.report.out

notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3320fc3f28abbb06e1d8
    on_success: change
    on_failure: always
    on_start: never
