version: 3.0.0.{build}-test

shallow_clone: true

environment:
  LUAROCKS_VER: 3.0.0

  matrix:
  - LUA: "lua 5.1"
    COMPILER: "vs"
    FILES: ".//?.lua"
  - LUA: "lua 5.1"
    COMPILER: "mingw"
    FILES: ".//build_spec.lua"
  - LUA: "lua 5.2"
    COMPILER: "vs"
    FILES: ".//?.lua"
  - LUA: "lua 5.2"
    COMPILER: "mingw"
    FILES: ".//build_spec.lua"
  - LUA: "lua 5.3"
    COMPILER: "vs"
    FILES: ".//?.lua"
  - LUA: "lua 5.3"
    COMPILER: "mingw"
    FILES: ".//build_spec.lua"
  - LUA: "luajit 2.0"
    COMPILER: "vs"
    FILES: ".//?.lua"
  - LUA: "luajit 2.0"
    COMPILER: "mingw"
    FILES: ".//build_spec.lua"
  - LUA: "luajit 2.1"
    COMPILER: "vs"
    FILES: ".//?.lua"
  - LUA: "luajit 2.1"
    COMPILER: "mingw"
    FILES: ".//build_spec.lua"

init:
# Setup Lua development/build environment
# Make VS 2015 command line tools available
- call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%
# Add MinGW compiler to the path
- set PATH=C:\MinGW\bin;%PATH%

before_build:
  - set PATH=C:\Python27\Scripts;%PATH% # Add directory containing 'pip' to PATH
  - pip install hererocks
  - hererocks lua_install --%LUA% --luarocks latest --target=%COMPILER%
  - call lua_install\bin\activate

build_script:
  - luarocks install busted 1> NUL 2> NUL
  - luarocks install cluacov 1> NUL 2> NUL

test_script:
  - busted -o gtest -v --lpath=%FILES% --exclude-tags=ssh,unix -Xhelper lua_dir=%CD%\lua_install,appveyor,%COMPILER%

after_test:
  - pip install codecov
  - luacov -c testrun/luacov.config
  - cd testrun && codecov -f luacov.report.out -X gcov
