version: 3.2.1.{build}-test

shallow_clone: true

matrix:
  fast_finish: true

environment:
  LUAROCKS_VER: 3.2.1

  matrix:
  # Lua 5.1 tests
  - LUAV: "5.1"
    LUAT: "lua"
    COMPILER: "vs"
    FILES: ""
    EXCLUDE: "integration"
  - LUAV: "5.1"
    LUAT: "lua"
    COMPILER: "vs"
    FILES: ""
    EXCLUDE: "unit"
  - LUAV: "5.1"
    LUAT: "lua"
    COMPILER: "mingw"
    FILES: "spec//build_spec.lua"
    EXCLUDE: ""
  # Lua 5.2 tests  
  - LUAV: "5.2"
    LUAT: "lua"
    COMPILER: "vs"
    FILES: ""
    EXCLUDE: "integration"
  - LUAV: "5.2"
    LUAT: "lua"
    COMPILER: "vs"
    FILES: ""
    EXCLUDE: "unit"
  - LUAV: "5.2"
    LUAT: "lua"
    COMPILER: "mingw"
    FILES: "spec//build_spec.lua"
    EXCLUDE: ""
  # Lua 5.3 tests
  - LUAV: "5.3"
    LUAT: "lua"
    COMPILER: "vs"
    FILES: ""
    EXCLUDE: "integration"
  - LUAV: "5.3"
    LUAT: "lua"
    COMPILER: "vs"
    FILES: ""
    EXCLUDE: "unit"
  - LUAV: "5.3"
    LUAT: "lua"
    COMPILER: "mingw"
    FILES: "spec//build_spec.lua"
    EXCLUDE: ""
  # LuaJIT 2.1 tests
  - LUAV: "2.1"
    LUAT: "luajit"
    COMPILER: "vs"
    FILES: ""
    EXCLUDE: "integration"
  - LUAV: "2.1"
    LUAT: "luajit"
    COMPILER: "vs"
    FILES: ""
    EXCLUDE: "unit"
  - LUAV: "2.1"
    LUAT: "luajit"
    COMPILER: "mingw"
    FILES: "spec//build_spec.lua"
    EXCLUDE: ""

init:
# Setup Lua development/build environment
# Make VS 2015 command line tools available
- call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%
# Add MinGW compiler to the path
- set PATH=C:\MinGW\bin;%PATH%

before_build:
  - set PATH=C:\Python27\Scripts;%PATH% # Add directory containing 'pip' to PATH
  - IF NOT EXIST lua_install-%LUAV%\bin\activate.bat ( pip install hererocks )
  - IF NOT EXIST lua_install-%LUAV%\bin\activate.bat ( hererocks lua_install-%LUAV% --%LUAT% %LUAV% --luarocks latest --target=%COMPILER% )
  - call lua_install-%LUAV%\bin\activate

build_script:
  - IF NOT EXIST lua_install-%LUAV%\bin\busted.bat ( luarocks install busted 1> NUL 2> NUL )
  - IF NOT EXIST lua_install-%LUAV%\bin\luacov.bat ( luarocks install cluacov 1> NUL 2> NUL )

test_script:
  - busted -o gtest -v --lpath=.//?.lua --exclude-tags=ssh,unix,%EXCLUDE% -Xhelper lua_dir=%CD%\lua_install-%LUAV%,appveyor,%COMPILER% %FILES%

after_test:
  - pip install codecov
  - luacov -c testrun/luacov.config
  - cd testrun && codecov -f luacov.report.out -X gcov

cache:
  - lua_install-5.1
  - lua_install-5.2
  - lua_install-5.3
  - lua_install-2.1
  - testrun/testing_cache-5.1
  - testrun/testing_cache-5.2
  - testrun/testing_cache-5.3
  - testrun/testing_cache-2.1
  - testrun/testing_server-5.1
  - testrun/testing_server-5.2
  - testrun/testing_server-5.3
  - testrun/testing_server-2.1
  - testrun/binary-samples
